app:
  jwt:
    secret-key: TestNisurtprl*/544f5gfg566323fgfgfgf93piervdfresponseinexceptio/ASSF45645454s
    response-object-identifier: "data"
    expiration-time: 8
  regex:
    email: ^(.+)@(.+)$
    password: ^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)[a-zA-Z\d\w\W]{8,}$

spring:
  datasource:
    url: jdbc:h2:mem:mydbuser;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  flyway:
    enabled: true
    locations: "classpath:db/migration"
  h2:
    console:
      enabled: true
      path: /h2-console
  jackson:
    property-naming-strategy: SNAKE_CASE
    serialization:
      write-date-keys-as-timestamps: false
      write-dates-as-timestamps: false
server:
  port: 8080

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true